export const SHOW_APP = "SHOW_APP"
export const NET_STATE = "NET_STATE"
export const GET_MQTT_MESSAGE = "MQTT_MESSAGE"
export const DEVICE_LIST = "DEVICE_LIST"
export const MQTT_CONNECTED = "MQTT_CONNECTED"